# This is a basic workflow to help you get started with Actions

name: Pro-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup node
      uses: actions/setup-node@v1
      with:
          node-version: "12.x"

    # Runs a set of commands using the runners shell
    - name: Build project
      run: npm install && npm run build
      #:)
    - name: docker build and push bash
      run: |
        docker login -u ${{ secrets.docker_name }} -p ${{ secrets.docker_pwd }}
        docker build -t veshen/menoble-web .
        docker push veshen/menoble-web
      #:)
        
    # - name: webfactory/ssh-agent
    #   uses: webfactory/ssh-agent@v0.4.1
    #   with:
    #       ssh-private-key: ${{ secrets.AWS_TOKEN }}
    # - name: Setup knownhosts
    #   run: ssh-keyscan ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
    # - name: Run SSH
    #   run: |
    #     ssh ${{ secrets.aws_ssh }} "cd /home/centos && sh ./test_panews_be_web.sh && exit"
            
